"""Fuse face, script, and subtitle embeddings into one scene-level vector.

This script reads the per-scene outputs generated by:

* ``make_face_vectors.py``
* ``make_script_embeddings.py``
* ``make_subtitle_embeddings.py``

For each movie, it aligns rows by ``scene_id``, normalizes each modality,
concatenates them into a single scene vector, and stores the full time-series
matrix for downstream similarity / retrieval work.

Output files are written to ``datasets/movienet/scene_fusion``:

* ``<movie_id>_scene_fused_vectors.npy`` - scene matrix, one row per scene
* ``<movie_id>_scene_valid_mask.npy`` - rows with at least one real modality
* ``<movie_id>_scene_modal_mask.npy`` - per-scene modality availability mask
* ``<movie_id>_scene_ids.json`` - scene ids in matrix order
* ``<movie_id>_scene_fusion_metadata.json`` - provenance and schema metadata
* ``<movie_id>_movie_vector.npy`` - mean pooled movie-level vector

The fused vector is:

    [face_embedding || script_embedding || subtitle_embedding]

where each modality is L2-normalized before concatenation.
"""

from __future__ import annotations

import argparse
import json
from hashlib import sha256
from pathlib import Path
from typing import Any

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
FACE_DIR = ROOT / "datasets" / "movienet" / "face_vectors"
SCRIPT_DIR = ROOT / "datasets" / "movienet" / "script_embeddings"
SUBTITLE_DIR = ROOT / "datasets" / "movienet" / "subtitle_embeddings"
JSON_DIR = ROOT / "datasets" / "movienet" / "scene_outputs"
OUTPUT_DIR = ROOT / "datasets" / "movienet" / "scene_fusion"

OUTPUT_FORMAT_VERSION = 1


def _sha256(path: Path) -> str:
    return sha256(path.read_bytes()).hexdigest()


def _load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def _load_optional_vector(path: Path) -> np.ndarray | None:
    if not path.is_file():
        return None
    return np.load(path)


def _load_optional_mask(path: Path, length: int) -> np.ndarray:
    if not path.is_file():
        return np.zeros(length, dtype=bool)
    mask = np.load(path)
    return np.asarray(mask, dtype=bool)


def _load_scene_ids(path: Path, fallback_length: int) -> list[int]:
    if path.is_file():
        with path.open("r", encoding="utf-8") as file:
            data = json.load(file)
        try:
            return [int(value) for value in data]
        except (TypeError, ValueError):
            pass
    return list(range(1, fallback_length + 1))


def _l2_normalize_rows(array: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(array, axis=1, keepdims=True)
    norms = np.where(norms == 0, 1.0, norms)
    return array / norms


def _align_by_scene_id(
    scene_ids: list[int],
    source_scene_ids: list[int],
    source_vectors: np.ndarray | None,
    source_mask: np.ndarray | None,
    dim: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Align a modality matrix to the target scene_id order."""
    vectors = np.full((len(scene_ids), dim), np.nan, dtype=np.float32)
    mask = np.zeros(len(scene_ids), dtype=bool)
    if source_vectors is None:
        return vectors, mask

    index = {int(scene_id): idx for idx, scene_id in enumerate(source_scene_ids)}
    for row_index, scene_id in enumerate(scene_ids):
        source_index = index.get(int(scene_id))
        if source_index is None:
            continue
        row_mask = True if source_mask is None else bool(source_mask[source_index])
        if not row_mask:
            continue
        row = np.asarray(source_vectors[source_index], dtype=np.float32)
        if row.ndim != 1 or row.shape[0] != dim:
            continue
        vectors[row_index] = row
        mask[row_index] = True
    return vectors, mask


def load_movie_inputs(movie_id: str) -> tuple[list[int], dict[str, Any]]:
    """Load whatever source files are available for one movie."""
    source_json = JSON_DIR / f"{movie_id}_integrated.json"
    if not source_json.is_file():
        raise FileNotFoundError(source_json)
    scenes = _load_json(source_json)
    scene_ids = [int(scene.get("scene_id")) for scene in scenes if scene.get("scene_id") is not None]
    if not scene_ids:
        raise ValueError(f"No scenes found in {source_json}")

    inputs = {
        "source_json": source_json,
        "scene_count": len(scene_ids),
        "face_vectors": _load_optional_vector(FACE_DIR / f"{movie_id}_face_vectors.npy"),
        "face_mask": _load_optional_mask(
            FACE_DIR / f"{movie_id}_face_valid_mask.npy",
            len(scene_ids),
        ),
        "face_scene_ids": _load_scene_ids(
            FACE_DIR / f"{movie_id}_scene_ids.json",
            len(scene_ids),
        ),
        "script_vectors": _load_optional_vector(SCRIPT_DIR / f"{movie_id}_script_embeddings.npy"),
        "script_mask": _load_optional_mask(
            SCRIPT_DIR / f"{movie_id}_script_valid_mask.npy",
            len(scene_ids),
        ),
        "script_scene_ids": _load_scene_ids(
            SCRIPT_DIR / f"{movie_id}_scene_ids.json",
            len(scene_ids),
        ),
        "subtitle_vectors": _load_optional_vector(
            SUBTITLE_DIR / f"{movie_id}_subtitle_embeddings.npy"
        ),
        "subtitle_mask": _load_optional_mask(
            SUBTITLE_DIR / f"{movie_id}_subtitle_valid_mask.npy",
            len(scene_ids),
        ),
        "subtitle_scene_ids": _load_scene_ids(
            SUBTITLE_DIR / f"{movie_id}_scene_ids.json",
            len(scene_ids),
        ),
    }
    return scene_ids, inputs


def build_fused_movie(movie_id: str, overwrite: bool, output_dir: Path = OUTPUT_DIR) -> None:
    scene_ids, inputs = load_movie_inputs(movie_id)
    output_dir.mkdir(parents=True, exist_ok=True)

    fused_path = output_dir / f"{movie_id}_scene_fused_vectors.npy"
    metadata_path = output_dir / f"{movie_id}_scene_fusion_metadata.json"
    if not overwrite and fused_path.is_file() and metadata_path.is_file():
        try:
            metadata = _load_json(metadata_path)
        except json.JSONDecodeError:
            metadata = {}
        if metadata.get("format_version") == OUTPUT_FORMAT_VERSION:
            if metadata.get("source_json_sha256") == _sha256(inputs["source_json"]):
                print(f"Skip current: {movie_id}")
                return

    face_vectors = inputs["face_vectors"]
    script_vectors = inputs["script_vectors"]
    subtitle_vectors = inputs["subtitle_vectors"]

    face_dim = 10 if face_vectors is None else int(face_vectors.shape[1])
    script_dim = 384 if script_vectors is None else int(script_vectors.shape[1])
    subtitle_dim = 384 if subtitle_vectors is None else int(subtitle_vectors.shape[1])

    face_aligned, face_mask = _align_by_scene_id(
        scene_ids,
        inputs["face_scene_ids"],
        face_vectors,
        inputs["face_mask"],
        face_dim,
    )
    script_aligned, script_mask = _align_by_scene_id(
        scene_ids,
        inputs["script_scene_ids"],
        script_vectors,
        inputs["script_mask"],
        script_dim,
    )
    subtitle_aligned, subtitle_mask = _align_by_scene_id(
        scene_ids,
        inputs["subtitle_scene_ids"],
        subtitle_vectors,
        inputs["subtitle_mask"],
        subtitle_dim,
    )

    # Missing modalities are filled with zeros after normalization so the
    # concatenated matrix remains finite. Separate masks preserve which
    # sources were actually present.
    face_filled = np.where(np.isnan(face_aligned), 0.0, face_aligned)
    script_filled = np.where(np.isnan(script_aligned), 0.0, script_aligned)
    subtitle_filled = np.where(np.isnan(subtitle_aligned), 0.0, subtitle_aligned)

    if face_mask.any():
        face_filled[face_mask] = _l2_normalize_rows(face_filled[face_mask])
    if script_mask.any():
        script_filled[script_mask] = _l2_normalize_rows(script_filled[script_mask])
    if subtitle_mask.any():
        subtitle_filled[subtitle_mask] = _l2_normalize_rows(subtitle_filled[subtitle_mask])

    fused = np.concatenate([face_filled, script_filled, subtitle_filled], axis=1).astype(
        np.float32
    )
    modality_mask = np.stack([face_mask, script_mask, subtitle_mask], axis=1)
    valid_mask = modality_mask.any(axis=1)

    fused_valid = fused[valid_mask]
    movie_vector = (
        fused_valid.mean(axis=0).astype(np.float32)
        if len(fused_valid)
        else np.full((fused.shape[1],), np.nan, dtype=np.float32)
    )

    np.save(fused_path, fused)
    np.save(output_dir / f"{movie_id}_scene_valid_mask.npy", valid_mask)
    np.save(output_dir / f"{movie_id}_scene_modal_mask.npy", modality_mask)
    np.save(output_dir / f"{movie_id}_movie_vector.npy", movie_vector)
    with (output_dir / f"{movie_id}_scene_ids.json").open("w", encoding="utf-8") as file:
        json.dump(scene_ids, file, ensure_ascii=False, indent=2)

    metadata = {
        "format_version": OUTPUT_FORMAT_VERSION,
        "movie_id": movie_id,
        "scene_count": len(scene_ids),
        "fused_dim": int(fused.shape[1]),
        "face_dim": face_dim,
        "script_dim": script_dim,
        "subtitle_dim": subtitle_dim,
        "source_json": str(inputs["source_json"]),
        "source_json_sha256": _sha256(inputs["source_json"]),
        "source_files": {
            "face_vectors": str(FACE_DIR / f"{movie_id}_face_vectors.npy"),
            "script_embeddings": str(SCRIPT_DIR / f"{movie_id}_script_embeddings.npy"),
            "subtitle_embeddings": str(
                SUBTITLE_DIR / f"{movie_id}_subtitle_embeddings.npy"
            ),
        },
        "valid_rows": int(valid_mask.sum()),
        "output_files": {
            "scene_fused_vectors": f"{movie_id}_scene_fused_vectors.npy",
            "scene_valid_mask": f"{movie_id}_scene_valid_mask.npy",
            "scene_modal_mask": f"{movie_id}_scene_modal_mask.npy",
            "movie_vector": f"{movie_id}_movie_vector.npy",
            "scene_ids": f"{movie_id}_scene_ids.json",
        },
        "concat_order": ["face", "script", "subtitle"],
        "normalization": "per-modality L2 before concatenation",
    }
    with metadata_path.open("w", encoding="utf-8") as file:
        json.dump(metadata, file, ensure_ascii=False, indent=2)

    print(
        f"Saved: {movie_id}_scene_fused_vectors.npy "
        f"shape={fused.shape} valid={int(valid_mask.sum())}/{len(valid_mask)}"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--movie-id", action="append", help="Can be passed multiple times.")
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--limit", type=int)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    json_files = sorted(JSON_DIR.glob("*_integrated.json"))
    movie_ids = [path.stem.removesuffix("_integrated") for path in json_files]
    if args.movie_id:
        requested = set(args.movie_id)
        movie_ids = [movie_id for movie_id in movie_ids if movie_id in requested]
    if args.limit is not None:
        movie_ids = movie_ids[: args.limit]

    for movie_id in movie_ids:
        build_fused_movie(movie_id, overwrite=args.overwrite, output_dir=args.output_dir)


if __name__ == "__main__":
    main()
